"""Regenerates agent/lib/triage-rubric.generated.ts from the Python triage's
_TRIAGE_SYSTEM_PROMPT so the eve agent scores with the exact same rubric.

Run from the repo root:
    PYTHONPATH=. .venv/bin/python escalation-agent/scripts/export-rubric.py
"""
import json
from pathlib import Path

from product_status.escalation_report import _TRIAGE_SYSTEM_PROMPT

PREVIOUS = "{previous_items}"
NEW = "{new_emails}"
MARKER = "PREVIOUSLY TRACKED ITEMS (JSON"

raw = _TRIAGE_SYSTEM_PROMPT
assert PREVIOUS in raw and NEW in raw and MARKER in raw, "unexpected prompt shape"
text = raw.replace(PREVIOUS, "__PREVIOUS_ITEMS__").replace(NEW, "__NEW_EMAILS__")
# Python's str.format escapes: "{{" -> "{" and "}}" -> "}".
text = text.replace("{{", "{").replace("}}", "}")
# The feedback block is injected right before the tracked-items section.
text = text.replace(MARKER, "__FEEDBACK__" + MARKER, 1)

out = Path(__file__).resolve().parent.parent / "agent" / "lib" / "triage-rubric.generated.ts"
out.write_text(
    "// GENERATED by scripts/export-rubric.py from product_status/escalation_report.py's\n"
    "// _TRIAGE_SYSTEM_PROMPT - do not edit by hand; re-run the script instead.\n"
    "export const TRIAGE_PROMPT_TEMPLATE = " + json.dumps(text, indent=2, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"wrote {out} ({len(text)} chars)")
