import { describe, expect, it } from "vitest";
import {
  isPartnerAuthored,
  looksAutoGenerated,
  normalizeSubject,
  resolveSender,
  stripHtml,
  type VitallyConversation,
} from "../agent/lib/filters";

const convo: VitallyConversation = { id: "c1", users: [{ id: "u1", name: "Pat", email: "pat@x.edu" }] };

describe("looksAutoGenerated", () => {
  it("drops calendar invites and OOO replies by subject", () => {
    expect(looksAutoGenerated("Invitation: Weekly sync @ Tue", "hi")).toBe(true);
    expect(looksAutoGenerated("Accepted: Weekly sync", "hi")).toBe(true);
    expect(looksAutoGenerated("Automatic reply: Re: question", "I am away")).toBe(true);
    expect(looksAutoGenerated("Out of office", "x")).toBe(true);
  });
  it("drops calendar-ish bodies", () => {
    expect(looksAutoGenerated("Hello", "Joining info: https://meet.google.com/x")).toBe(true);
  });
  it("keeps real human mail", () => {
    expect(looksAutoGenerated("Registration is broken", "Students cannot register.")).toBe(false);
  });
});

describe("isPartnerAuthored", () => {
  it("trusts type inbound", () => {
    expect(isPartnerAuthored({ type: "inbound", from: { id: "zzz" } }, convo)).toBe(true);
  });
  it("rescues mislabelled outbound messages sent by a conversation user", () => {
    expect(isPartnerAuthored({ type: "outbound", from: { id: "u1" } }, convo)).toBe(true);
  });
  it("rejects a Stellic outbound message", () => {
    expect(isPartnerAuthored({ type: "outbound", from: { id: "admin1" } }, convo)).toBe(false);
    expect(isPartnerAuthored({ type: "outbound" }, convo)).toBe(false);
  });
});

describe("helpers", () => {
  it("strips html tags", () => {
    expect(stripHtml("<p>Hello <b>world</b></p>")).toBe("Hello  world");
    expect(stripHtml(null)).toBe("");
  });
  it("normalizes Re:/Fwd: chains", () => {
    expect(normalizeSubject("RE: Fwd:  Registration   Down")).toBe("registration down");
  });
  it("resolves sender names, falling back to the id", () => {
    expect(resolveSender({ from: { id: "u1" } }, convo)).toBe("Pat");
    expect(resolveSender({ from: { id: "other" } }, convo)).toBe("other");
    expect(resolveSender({}, convo)).toBe("(unknown)");
  });
});
