/**
 * Mechanical (non-LLM) pre-filtering of Vitally messages. Ports
 * `_looks_auto_generated`, `_is_partner_authored`, `_strip_html` and
 * `_normalize_subject_for_match` from `product_status/escalation_report.py`.
 */

export interface VitallyParticipant {
  id?: string;
  [key: string]: unknown;
}

export interface VitallyMessage {
  type?: string;
  timestamp?: string;
  createdAt?: string;
  message?: string | null;
  from?: VitallyParticipant | null;
  [key: string]: unknown;
}

export interface VitallyConversation {
  id: string;
  subject?: string | null;
  source?: string;
  updatedAt?: string;
  users?: Array<{ id?: string; name?: string; email?: string }>;
  messages?: VitallyMessage[];
  [key: string]: unknown;
}

const CALENDAR_SUBJECT_RE =
  /^(invitation|accepted|declined|tentative|updated invitation|canceled event|cancelled event|new event|updated event|event reminder|reminder|updated invite|invite)\s*:/i;
const AUTO_REPLY_SUBJECT_RE =
  /(automatic reply|auto-?reply|out of office|away from (my|the) (email|office)|vacation response)/i;
const AUTO_GENERATED_BODY_MARKERS = [
  "you have been invited by",
  "this event has been canceled",
  "this event has been cancelled",
  "when: ",
  "where: ",
  "joining info",
  "google meet joining info",
];

const NAMED_ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
  rsquo: "\u2019",
  lsquo: "\u2018",
  rdquo: "\u201d",
  ldquo: "\u201c",
  ndash: "\u2013",
  mdash: "\u2014",
  hellip: "\u2026",
};

/** Decodes the common named and numeric HTML entities (`&amp;`, `&#39;`, `&#x27;`, ...). Unknown ones are left as-is. */
export function decodeHtmlEntities(value: string): string {
  return value.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (match, body: string) => {
    if (body[0] === "#") {
      const code = body[1]?.toLowerCase() === "x" ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
      return Number.isFinite(code) && code > 0 && code <= 0x10ffff ? String.fromCodePoint(code) : match;
    }
    return NAMED_ENTITIES[body.toLowerCase()] ?? match;
  });
}

export function stripHtml(value: string | null | undefined): string {
  if (!value) return "";
  // Strip tags first, then decode, so an escaped "&lt;b&gt;" is never mistaken for markup.
  return decodeHtmlEntities(value.replace(/<[^>]+>/g, " ")).trim();
}

/**
 * Conservative: only the obvious, high-volume cases (calendar invites/
 * responses, OOO auto-replies). Subtler noise is left to the model per the
 * rubric's SCOPE section.
 */
export function looksAutoGenerated(subject: string, bodyText: string): boolean {
  if (CALENDAR_SUBJECT_RE.test(subject.trim())) return true;
  if (AUTO_REPLY_SUBJECT_RE.test(subject)) return true;
  const lowered = bodyText.toLowerCase();
  return AUTO_GENERATED_BODY_MARKERS.some((marker) => lowered.includes(marker));
}

/**
 * Partner-authored when Vitally says `type: "inbound"`, or - because that
 * field mislabels some real partner replies as "outbound" - when the
 * message's `from.id` is one of the conversation's own external `users`.
 */
export function isPartnerAuthored(message: VitallyMessage, conversation: VitallyConversation): boolean {
  if (message.type === "inbound") return true;
  const senderId = message.from?.id;
  if (!senderId) return false;
  return (conversation.users ?? []).some((user) => user.id === senderId);
}

export function resolveSender(message: VitallyMessage, conversation: VitallyConversation): string {
  const senderId = message.from?.id;
  for (const user of conversation.users ?? []) {
    if (user.id === senderId) return user.name || user.email || senderId || "(unknown)";
  }
  return senderId || "(unknown)";
}

/** Case/prefix-insensitive subject key (Re:/Fwd: chains differ in casing). */
export function normalizeSubject(subject: string): string {
  let normalized = (subject || "").trim().toLowerCase().replace(/\s+/g, " ");
  for (;;) {
    const stripped = normalized.replace(/^(re|fw|fwd):\s*/, "");
    if (stripped === normalized) break;
    normalized = stripped;
  }
  return normalized;
}
