import {
  ELIGIBLE_SOURCES,
  MAX_CONVERSATIONS_PER_ACCOUNT,
} from "./config";
import {
  isPartnerAuthored,
  looksAutoGenerated,
  resolveSender,
  stripHtml,
  type VitallyConversation,
} from "./filters";

const VITALLY_BASE_URL = "https://rest.vitally.io/resources";
const MAX_RETRIES = 4;
const INITIAL_BACKOFF_MS = 1000;

export interface SourceEmail {
  from: string;
  subject: string;
  date: string;
  body: string;
  vitallyConversationId: string;
}

export interface VitallyApi {
  listAccountConversations(accountId: string): AsyncGenerator<VitallyConversation>;
  getConversation(conversationId: string): Promise<VitallyConversation>;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

/** Read-only Vitally REST client (Basic auth, retry on 429/network errors). */
export function createVitallyClient(accessToken = process.env.VITALLY_ACCESS_TOKEN): VitallyApi {
  if (!accessToken) throw new Error("VITALLY_ACCESS_TOKEN is not set - see .env.example");
  const authHeader = "Basic " + Buffer.from(`${accessToken}:`).toString("base64");

  async function get(path: string, params: Record<string, string | number> = {}): Promise<any> {
    const url = new URL(`${VITALLY_BASE_URL}${path}`);
    for (const [key, value] of Object.entries(params)) url.searchParams.set(key, String(value));
    let backoff = INITIAL_BACKOFF_MS;
    let lastError: unknown;
    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        const response = await fetch(url, {
          headers: { Authorization: authHeader },
          signal: AbortSignal.timeout(30_000),
        });
        if (response.status === 429 && attempt < MAX_RETRIES) {
          lastError = new Error(`Vitally API rate limited (attempt ${attempt})`);
        } else if (!response.ok) {
          throw new Error(`Vitally API error ${response.status}: ${(await response.text()).slice(0, 500)}`);
        } else {
          return await response.json();
        }
      } catch (error) {
        if (error instanceof Error && error.message.startsWith("Vitally API error")) throw error;
        lastError = error;
      }
      if (attempt < MAX_RETRIES) {
        await sleep(backoff);
        backoff *= 2;
      }
    }
    throw new Error(`Vitally API: exhausted retries (${String(lastError)})`);
  }

  return {
    async *listAccountConversations(accountId) {
      let cursor: string | undefined;
      for (;;) {
        const params: Record<string, string | number> = { limit: 25 };
        if (cursor) params.from = cursor;
        const payload = await get(`/accounts/${accountId}/conversations`, params);
        for (const conversation of payload.results ?? []) yield conversation as VitallyConversation;
        if (payload.atEnd || !payload.next) break;
        cursor = payload.next as string;
      }
    },
    async getConversation(conversationId) {
      return (await get(`/conversations/${conversationId}`)) as VitallyConversation;
    },
  };
}

const toMs = (iso: string | undefined): number => {
  const ms = iso ? Date.parse(iso) : NaN;
  return Number.isNaN(ms) ? NaN : ms;
};

/**
 * Every partner-authored, non-auto-generated message (source in
 * ELIGIBLE_SOURCES) for one account, strictly newer than `sinceIso`, oldest
 * first. Conversations arrive sorted by updatedAt desc, so the walk stops at
 * the first one that is entirely too old to matter. Port of
 * `_collect_new_human_emails`.
 */
export async function collectNewHumanEmails(
  vitally: VitallyApi,
  accountId: string,
  sinceIso: string,
): Promise<SourceEmail[]> {
  const sinceMs = toMs(sinceIso);
  const candidates: SourceEmail[] = [];
  let checked = 0;
  for await (const summary of vitally.listAccountConversations(accountId)) {
    checked += 1;
    if (checked > MAX_CONVERSATIONS_PER_ACCOUNT) break;
    if (!(ELIGIBLE_SOURCES as readonly string[]).includes(summary.source ?? "")) continue;
    const updatedMs = toMs(summary.updatedAt);
    if (!Number.isNaN(updatedMs) && !Number.isNaN(sinceMs) && updatedMs < sinceMs) break;
    const full = await vitally.getConversation(summary.id);
    const subject = full.subject || "(no subject)";
    for (const message of full.messages ?? []) {
      if (!isPartnerAuthored(message, full)) continue;
      const timestamp = message.timestamp || message.createdAt || "";
      const timestampMs = toMs(timestamp);
      if (!timestamp || Number.isNaN(timestampMs) || (!Number.isNaN(sinceMs) && timestampMs <= sinceMs)) continue;
      const bodyText = stripHtml(message.message);
      if (!bodyText || looksAutoGenerated(subject, bodyText)) continue;
      candidates.push({
        from: resolveSender(message, full),
        subject,
        date: timestamp,
        body: bodyText.slice(0, 4000),
        vitallyConversationId: summary.id,
      });
    }
  }
  candidates.sort((a, b) => Date.parse(a.date) - Date.parse(b.date));
  return candidates;
}

export function vitallyConversationUrl(conversationId: string): string | null {
  const subdomain = process.env.VITALLY_APP_SUBDOMAIN;
  if (!subdomain || !conversationId) return null;
  return `https://${subdomain}.vitally.io/conversations/active/${conversationId}`;
}

export function vitallyAccountUrl(accountId: string): string | null {
  const subdomain = process.env.VITALLY_APP_SUBDOMAIN;
  if (!subdomain) return null;
  return `https://${subdomain}.vitally.io/accounts/${accountId}`;
}
